export const globalCountries = [
    { id: 'Afeganistão', name: 'Afeganistão', code: 'af' },
    { id: 'África do Sul', name: 'África do Sul', code: 'za' },
    { id: 'Albânia', name: 'Albânia', code: 'al' },
    { id: 'Alemanha', name: 'Alemanha', code: 'de' },
    { id: 'Andorra', name: 'Andorra', code: 'ad' },
    { id: 'Angola', name: 'Angola', code: 'ao' },
    { id: 'Anguila', name: 'Anguila', code: 'ai' },
    { id: 'Antártida', name: 'Antártida', code: 'aq' },
    { id: 'Antígua e Barbuda', name: 'Antígua e Barbuda', code: 'ag' },
    { id: 'Arábia Saudita', name: 'Arábia Saudita', code: 'sa' },
    { id: 'Argélia', name: 'Argélia', code: 'dz' },
    { id: 'Argentina', name: 'Argentina', code: 'ar' },
    { id: 'Armênia', name: 'Armênia', code: 'am' },
    { id: 'Aruba', name: 'Aruba', code: 'aw' },
    { id: 'Austrália', name: 'Austrália', code: 'au' },
    { id: 'Áustria', name: 'Áustria', code: 'at' },
    { id: 'Azerbaijão', name: 'Azerbaijão', code: 'az' },
    { id: 'Bahamas', name: 'Bahamas', code: 'bs' },
    { id: 'Bangladesh', name: 'Bangladesh', code: 'bd' },
    { id: 'Barbados', name: 'Barbados', code: 'bb' },
    { id: 'Bahrein', name: 'Bahrein', code: 'bh' },
    { id: 'Bélgica', name: 'Bélgica', code: 'be' },
    { id: 'Belize', name: 'Belize', code: 'bz' },
    { id: 'Benim', name: 'Benim', code: 'bj' },
    { id: 'Bermudas', name: 'Bermudas', code: 'bm' },
    { id: 'Bielorrússia', name: 'Bielorrússia', code: 'by' },
    { id: 'Bolívia', name: 'Bolívia', code: 'bo' },
    { id: 'Bósnia e Herzegovina', name: 'Bósnia e Herzegovina', code: 'ba' },
    { id: 'Botsuana', name: 'Botsuana', code: 'bw' },
    { id: 'Brasil', name: 'Brasil', code: 'br' },
    { id: 'Brunei', name: 'Brunei', code: 'bn' },
    { id: 'Bulgária', name: 'Bulgária', code: 'bg' },
    { id: 'Burquina Faso', name: 'Burquina Faso', code: 'bf' },
    { id: 'Burundi', name: 'Burundi', code: 'bi' },
    { id: 'Butão', name: 'Butão', code: 'bt' },
    { id: 'Cabo Verde', name: 'Cabo Verde', code: 'cv' },
    { id: 'Camboja', name: 'Camboja', code: 'kh' },
    { id: 'Camarões', name: 'Camarões', code: 'cm' },
    { id: 'Canadá', name: 'Canadá', code: 'ca' },
    { id: 'Catar', name: 'Catar', code: 'qa' },
    { id: 'Cazaquistão', name: 'Cazaquistão', code: 'kz' },
    { id: 'Chade', name: 'Chade', code: 'td' },
    { id: 'Chile', name: 'Chile', code: 'cl' },
    { id: 'China', name: 'China', code: 'cn' },
    { id: 'Chipre', name: 'Chipre', code: 'cy' },
    { id: 'Colômbia', name: 'Colômbia', code: 'co' },
    { id: 'Comores', name: 'Comores', code: 'km' },
    { id: 'Congo-Brazzaville', name: 'Congo-Brazzaville', code: 'cg' },
    { id: 'Congo-Kinshasa', name: 'Congo-Kinshasa', code: 'cd' },
    { id: 'Coreia do Norte', name: 'Coreia do Norte', code: 'kp' },
    { id: 'Coreia do Sul', name: 'Coreia do Sul', code: 'kr' },
    { id: 'Costa do Marfim', name: 'Costa do Marfim', code: 'ci' },
    { id: 'Costa Rica', name: 'Costa Rica', code: 'cr' },
    { id: 'Croácia', name: 'Croácia', code: 'hr' },
    { id: 'Cuba', name: 'Cuba', code: 'cu' },
    { id: 'Curação', name: 'Curação', code: 'cw' },
    { id: 'Dinamarca', name: 'Dinamarca', code: 'dk' },
    { id: 'Djibuti', name: 'Djibuti', code: 'dj' },
    { id: 'Dominica', name: 'Dominica', code: 'dm' },
    { id: 'Egito', name: 'Egito', code: 'eg' },
    { id: 'El Salvador', name: 'El Salvador', code: 'sv' },
    { id: 'Emirados Árabes Unidos', name: 'Emirados Árabes Unidos', code: 'ae' },
    { id: 'Equador', name: 'Equador', code: 'ec' },
    { id: 'Eritreia', name: 'Eritreia', code: 'er' },
    { id: 'Eslováquia', name: 'Eslováquia', code: 'sk' },
    { id: 'Eslovênia', name: 'Eslovênia', code: 'si' },
    { id: 'Espanha', name: 'Espanha', code: 'es' },
    { id: 'Estados Unidos', name: 'Estados Unidos', code: 'us' },
    { id: 'Estônia', name: 'Estônia', code: 'ee' },
    { id: 'Etiópia', name: 'Etiópia', code: 'et' },
    { id: 'Fiji', name: 'Fiji', code: 'fj' },
    { id: 'Filipinas', name: 'Filipinas', code: 'ph' },
    { id: 'Finlândia', name: 'Finlândia', code: 'fi' },
    { id: 'França', name: 'França', code: 'fr' },
    { id: 'Gabão', name: 'Gabão', code: 'ga' },
    { id: 'Gâmbia', name: 'Gâmbia', code: 'gm' },
    { id: 'Gana', name: 'Gana', code: 'gh' },
    { id: 'Geórgia', name: 'Geórgia', code: 'ge' },
    { id: 'Gibraltar', name: 'Gibraltar', code: 'gi' },
    { id: 'Granada', name: 'Granada', code: 'gd' },
    { id: 'Grécia', name: 'Grécia', code: 'gr' },
    { id: 'Groenlândia', name: 'Groenlândia', code: 'gl' },
    { id: 'Guadalupe', name: 'Guadalupe', code: 'gp' },
    { id: 'Guam', name: 'Guam', code: 'gu' },
    { id: 'Guatemala', name: 'Guatemala', code: 'gt' },
    { id: 'Guernsey', name: 'Guernsey', code: 'gg' },
    { id: 'Guiana', name: 'Guiana', code: 'gy' },
    { id: 'Guiana Francesa', name: 'Guiana Francesa', code: 'gf' },
    { id: 'Guiné', name: 'Guiné', code: 'gn' },
    { id: 'Guiné Equatorial', name: 'Guiné Equatorial', code: 'gq' },
    { id: 'Guiné-Bissau', name: 'Guiné-Bissau', code: 'gw' },
    { id: 'Haiti', name: 'Haiti', code: 'ht' },
    { id: 'Honduras', name: 'Honduras', code: 'hn' },
    { id: 'Hong Kong', name: 'Hong Kong', code: 'hk' },
    { id: 'Hungria', name: 'Hungria', code: 'hu' },
    { id: 'Iêmen', name: 'Iêmen', code: 'ye' },
    { id: 'Ilha de Man', name: 'Ilha de Man', code: 'im' },
    { id: 'Ilha Christmas', name: 'Ilha Christmas', code: 'cx' },
    { id: 'Ilha Norfolk', name: 'Ilha Norfolk', code: 'nf' },
    { id: 'Ilhas Aland', name: 'Ilhas Aland', code: 'ax' },
    { id: 'Ilhas Cayman', name: 'Ilhas Cayman', code: 'ky' },
    { id: 'Ilhas Cocos', name: 'Ilhas Cocos', code: 'cc' },
    { id: 'Ilhas Cook', name: 'Ilhas Cook', code: 'ck' },
    { id: 'Ilhas Faroé', name: 'Ilhas Faroé', code: 'fo' },
    { id: 'Ilhas Malvinas', name: 'Ilhas Malvinas', code: 'fk' },
    { id: 'Ilhas Marianas do Norte', name: 'Ilhas Marianas do Norte', code: 'mp' },
    { id: 'Ilhas Marshall', name: 'Ilhas Marshall', code: 'mh' },
    { id: 'Ilhas Salomão', name: 'Ilhas Salomão', code: 'sb' },
    { id: 'Ilhas Turcas e Caicos', name: 'Ilhas Turcas e Caicos', code: 'tc' },
    { id: 'Ilhas Virgens Britânicas', name: 'Ilhas Virgens Britânicas', code: 'vg' },
    { id: 'Ilhas Virgens Americanas', name: 'Ilhas Virgens Americanas', code: 'vi' },
    { id: 'Índia', name: 'Índia', code: 'in' },
    { id: 'Indonésia', name: 'Indonésia', code: 'id' },
    { id: 'Irã', name: 'Irã', code: 'ir' },
    { id: 'Iraque', name: 'Iraque', code: 'iq' },
    { id: 'Irlanda', name: 'Irlanda', code: 'ie' },
    { id: 'Islândia', name: 'Islândia', code: 'is' },
    { id: 'Israel', name: 'Israel', code: 'il' },
    { id: 'Itália', name: 'Itália', code: 'it' },
    { id: 'Jamaica', name: 'Jamaica', code: 'jm' },
    { id: 'Japão', name: 'Japão', code: 'jp' },
    { id: 'Jersey', name: 'Jersey', code: 'je' },
    { id: 'Jordânia', name: 'Jordânia', code: 'jo' },
    { id: 'Quiribati', name: 'Quiribati', code: 'ki' },
    { id: 'Kuwait', name: 'Kuwait', code: 'kw' },
    { id: 'Laos', name: 'Laos', code: 'la' },
    { id: 'Lesoto', name: 'Lesoto', code: 'ls' },
    { id: 'Letônia', name: 'Letônia', code: 'lv' },
    { id: 'Líbano', name: 'Líbano', code: 'lb' },
    { id: 'Libéria', name: 'Libéria', code: 'lr' },
    { id: 'Líbia', name: 'Líbia', code: 'ly' },
    { id: 'Liechtenstein', name: 'Liechtenstein', code: 'li' },
    { id: 'Lituânia', name: 'Lituânia', code: 'lt' },
    { id: 'Luxemburgo', name: 'Luxemburgo', code: 'lu' },
    { id: 'Macau', name: 'Macau', code: 'mo' },
    { id: 'Macedônia do Norte', name: 'Macedônia do Norte', code: 'mk' },
    { id: 'Madagascar', name: 'Madagascar', code: 'mg' },
    { id: 'Malásia', name: 'Malásia', code: 'my' },
    { id: 'Malaui', name: 'Malaui', code: 'mw' },
    { id: 'Maldivas', name: 'Maldivas', code: 'mv' },
    { id: 'Mali', name: 'Mali', code: 'ml' },
    { id: 'Malta', name: 'Malta', code: 'mt' },
    { id: 'Marrocos', name: 'Marrocos', code: 'ma' },
    { id: 'Martinica', name: 'Martinica', code: 'mq' },
    { id: 'Maurício', name: 'Maurício', code: 'mu' },
    { id: 'Mauritânia', name: 'Mauritânia', code: 'mr' },
    { id: 'Mayotte', name: 'Mayotte', code: 'yt' },
    { id: 'México', name: 'México', code: 'mx' },
    { id: 'Micronésia', name: 'Micronésia', code: 'fm' },
    { id: 'Moçambique', name: 'Moçambique', code: 'mz' },
    { id: 'Moldávia', name: 'Moldávia', code: 'md' },
    { id: 'Mônaco', name: 'Mônaco', code: 'mc' },
    { id: 'Mongólia', name: 'Mongólia', code: 'mn' },
    { id: 'Montenegro', name: 'Montenegro', code: 'me' },
    { id: 'Montserrat', name: 'Montserrat', code: 'ms' },
    { id: 'Miamar', name: 'Miamar', code: 'mm' },
    { id: 'Namíbia', name: 'Namíbia', code: 'na' },
    { id: 'Nauru', name: 'Nauru', code: 'nr' },
    { id: 'Nepal', name: 'Nepal', code: 'np' },
    { id: 'Nicarágua', name: 'Nicarágua', code: 'ni' },
    { id: 'Níger', name: 'Níger', code: 'ne' },
    { id: 'Nigéria', name: 'Nigéria', code: 'ng' },
    { id: 'Niue', name: 'Niue', code: 'nu' },
    { id: 'Noruega', name: 'Noruega', code: 'no' },
    { id: 'Nova Caledônia', name: 'Nova Caledônia', code: 'nc' },
    { id: 'Nova Zelândia', name: 'Nova Zelândia', code: 'nz' },
    { id: 'Omã', name: 'Omã', code: 'om' },
    { id: 'Países Baixos', name: 'Países Baixos', code: 'nl' },
    { id: 'Palau', name: 'Palau', code: 'pw' },
    { id: 'Palestina', name: 'Palestina', code: 'ps' },
    { id: 'Panamá', name: 'Panamá', code: 'pa' },
    { id: 'Papua-Nova Guiné', name: 'Papua-Nova Guiné', code: 'pg' },
    { id: 'Paquistão', name: 'Paquistão', code: 'pk' },
    { id: 'Paraguai', name: 'Paraguai', code: 'py' },
    { id: 'Peru', name: 'Peru', code: 'pe' },
    { id: 'Polinésia Francesa', name: 'Polinésia Francesa', code: 'pf' },
    { id: 'Polônia', name: 'Polônia', code: 'pl' },
    { id: 'Porto Rico', name: 'Porto Rico', code: 'pr' },
    { id: 'Portugal', name: 'Portugal', code: 'pt' },
    { id: 'Quênia', name: 'Quênia', code: 'ke' },
    { id: 'Quirguistão', name: 'Quirguistão', code: 'kg' },
    { id: 'Reino Unido', name: 'Reino Unido', code: 'gb' },
    { id: 'República Centro-Africana', name: 'República Centro-Africana', code: 'cf' },
    { id: 'República Tcheca', name: 'República Tcheca', code: 'cz' },
    { id: 'República Dominicana', name: 'República Dominicana', code: 'do' },
    { id: 'Reunião', name: 'Reunião', code: 're' },
    { id: 'Romênia', name: 'Romênia', code: 'ro' },
    { id: 'Ruanda', name: 'Ruanda', code: 'rw' },
    { id: 'Rússia', name: 'Rússia', code: 'ru' },
    { id: 'Saara Ocidental', name: 'Saara Ocidental', code: 'eh' },
    { id: 'Samoa Americana', name: 'Samoa Americana', code: 'as' },
    { id: 'Samoa', name: 'Samoa', code: 'ws' },
    { id: 'San Marino', name: 'San Marino', code: 'sm' },
    { id: 'Santa Helena', name: 'Santa Helena', code: 'sh' },
    { id: 'Santa Lúcia', name: 'Santa Lúcia', code: 'lc' },
    { id: 'São Bartolomeu', name: 'São Bartolomeu', code: 'bl' },
    { id: 'São Cristóvão e Névis', name: 'São Cristóvão e Névis', code: 'kn' },
    { id: 'São Martinho', name: 'São Martinho', code: 'mf' },
    { id: 'São Pedro e Miquelão', name: 'São Pedro e Miquelão', code: 'pm' },
    { id: 'São Vicente e Granadinas', name: 'São Vicente e Granadinas', code: 'vc' },
    { id: 'São Tomé e Príncipe', name: 'São Tomé e Príncipe', code: 'st' },
    { id: 'Senegal', name: 'Senegal', code: 'sn' },
    { id: 'Sérvia', name: 'Sérvia', code: 'rs' },
    { id: 'Seicheles', name: 'Seicheles', code: 'sc' },
    { id: 'Serra Leoa', name: 'Serra Leoa', code: 'sl' },
    { id: 'Singapura', name: 'Singapura', code: 'sg' },
    { id: 'Sint Maarten', name: 'Sint Maarten', code: 'sx' },
    { id: 'Síria', name: 'Síria', code: 'sy' },
    { id: 'Somália', name: 'Somália', code: 'so' },
    { id: 'Sri Lanka', name: 'Sri Lanka', code: 'lk' },
    { id: 'Suazilândia', name: 'Suazilândia', code: 'sz' },
    { id: 'Sudão', name: 'Sudão', code: 'sd' },
    { id: 'Sudão do Sul', name: 'Sudão do Sul', code: 'ss' },
    { id: 'Suécia', name: 'Suécia', code: 'se' },
    { id: 'Suíça', name: 'Suíça', code: 'ch' },
    { id: 'Suriname', name: 'Suriname', code: 'sr' },
    { id: 'Svalbard e Jan Mayen', name: 'Svalbard e Jan Mayen', code: 'sj' },
    { id: 'Tailândia', name: 'Tailândia', code: 'th' },
    { id: 'Taiwan', name: 'Taiwan', code: 'tw' },
    { id: 'Tajiquistão', name: 'Tajiquistão', code: 'tj' },
    { id: 'Tanzânia', name: 'Tanzânia', code: 'tz' },
    { id: 'Territórios Franceses do Sul', name: 'Territórios Franceses do Sul', code: 'tf' },
    { id: 'Território Britânico do Oceano Índico', name: 'Território Britânico do Oceano Índico', code: 'io' },
    { id: 'Timor-Leste', name: 'Timor-Leste', code: 'tl' },
    { id: 'Togo', name: 'Togo', code: 'tg' },
    { id: 'Toquelau', name: 'Toquelau', code: 'tk' },
    { id: 'Tonga', name: 'Tonga', code: 'to' },
    { id: 'Trinidad e Tobago', name: 'Trinidad e Tobago', code: 'tt' },
    { id: 'Tunísia', name: 'Tunísia', code: 'tn' },
    { id: 'Turcomenistão', name: 'Turcomenistão', code: 'tm' },
    { id: 'Turquia', name: 'Turquia', code: 'tr' },
    { id: 'Tuvalu', name: 'Tuvalu', code: 'tv' },
    { id: 'Ucrânia', name: 'Ucrânia', code: 'ua' },
    { id: 'Uganda', name: 'Uganda', code: 'ug' },
    { id: 'Uruguai', name: 'Uruguai', code: 'uy' },
    { id: 'Uzbequistão', name: 'Uzbequistão', code: 'uz' },
    { id: 'Vanuatu', name: 'Vanuatu', code: 'vu' },
    { id: 'Vaticano', name: 'Vaticano', code: 'va' },
    { id: 'Venezuela', name: 'Venezuela', code: 've' },
    { id: 'Vietnã', name: 'Vietnã', code: 'vn' },
    { id: 'Wallis e Futuna', name: 'Wallis e Futuna', code: 'wf' },
    { id: 'Zâmbia', name: 'Zâmbia', code: 'zm' },
    { id: 'Zimbábue', name: 'Zimbábue', code: 'zw' }
];
